version: "4.0"

services:
  client:
    container_name: client-container
    image: client-image
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  server:
    container_name: server-container
    image: server-image
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
